#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    rm -rf /var/mobile/Containers/Data/Application/*/Library/Caches/ShuDongTweak 2>/dev/null || true
    killall -9 whou 2>/dev/null || true
fi

exit 0
